### ISSUE TITLE
转载权申请

### ISSUE THREAD

**Issue by xinpengfei520** [GitCode8/GitCode#19]
哈喽，您好！

我叫大飞，我是一个 Android Coder，我是在掘金上看到你的，觉得你的文章写的非常棒！我平时也比较喜欢学习和分享，我不知道如何联系您，因此我只能在这里给提个 issue 了。

我读了你的「代码洁癖症的我，学习Lint学到心态爆炸」 这篇文章，觉得写的非常好，因此我想申请转载您的这篇文章到我的公众号，好文章是需要分享的，以便分享给更多的读者朋友们，真真切切的帮助到他们，当然我会注明转载的原文地址和出处的，如果可以的话，你可以加下我的微信：542270559，有机会的话我们可以互相学习和交流一下。

Best Regards.

**Comment by xxm-sz** [comment]
Hi，你可以直接转载，备注出处即可。
